### ISSUE TITLE
KeyError when transferring playlist

### ISSUE THREAD

**Issue by misterissac** [abhishekmj303/ytm2spt#10]
Hi there, I've just installed the software and am trying to transfer a playlist when I encountered this error:

(base) issaccheung@Issacs-MacBook-Air ytm2spt-main % python src/main.py -yt "PLZIy8xuFMWodrHViO7D3TqdCgOqDFegLP"
INFO - Youtube Playlist ID: PLZIy8xuFMWodrHViO7D3TqdCgOqDFegLP
INFO - Youtube Playlist Name: All
Traceback (most recent call last):
  File "/Users/issaccheung/ytm2spt-main/src/main.py", line 149, in <module>
    spotify_id = get_spotify_playlist_id(spotify_arg, spotify_playlist_name)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/issaccheung/ytm2spt-main/src/main.py", line 51, in get_spotify_playlist_id
    return sp.create_playlist(yt.get_playlist_title())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/issaccheung/ytm2spt-main/src/spotify.py", line 97, in create_playlist
    return playlist['id']
           ~~~~~~~~^^^^^^
KeyError: 'id'

Any help is appreciated, thanks!

**Comment by abhishekmj303** [comment]
In `.env` the `SPOTIFY_USER_ID` is not the email address. You will get the username here: https://www.spotify.com/in-en/account/profile/

Run this again after editing the file
```
source .env
```

**Comment by misterissac** [comment]
That fixed it, thanks a lot!!
