### ISSUE TITLE
Cannot download on Windows: virus detected

### ISSUE THREAD

**Issue by FlorineC** [abhishekmj303/ytm2spt#14]
**Describe the bug**
I cannot download the release 1.0.0 on WIndows. My browser say a virus is detected (Chrome and Firefox).

**To Reproduce**
- [x] Git cloned or downloaded the repo.
- [ ] Got credentials from spotify developer account.
- [ ] Install dependecies: `pip install -r requirements.txt`
- [ ] Youtube OAuth: `ytmusicapi oauth`
- [ ] Set environment variables by: '...'
- [ ] Command ran: '...'
- [ ] Got Error: '...'

**Expected behavior**
I want to download the release.

**Screenshots**
![image](https://github.com/user-attachments/assets/69ceb18a-1b7e-4f91-86c5-71c830cd869a)

**Device (please complete the following information):**
 - OS: Windows

**Comment by BerkeSinanYetkin** [comment]
try using edge if it doesn't behave itself wget it through powershell like so

`wget https://github.com/abhishekmj303/ytm2spt/releases/download/v1.0.0/ytm2spt-v1.0.0-windows.zip -OutFile C:\Users\**INSERT YOUR USER**\Downloads\yt2sptfy.zip`

**Comment by FlorineC** [comment]
Hello,
Same issue with Edge. With Powershell, it is automatically deleted by Windows in a few seconds.

**Comment by abhishekmj303** [comment]
@FlorineC

The tool used to compile the code to exe (Nuitka) itself is flagged as a virus [see here](https://github.com/Nuitka/Nuitka/issues/1470) and [here](https://nuitka.net/user-documentation/common-issue-solutions.html#windows-virus-scanners).

You can try to allow this particular file in the windows defender history.

If you are still not able to download the file. You can install python and try the manual method of cloning the repo and running it from the terminal.

**Comment by FlorineC** [comment]
I added it to Windows Defender and it worked. Thanks!
