### ISSUE TITLE
secret Client ID problem

### ISSUE THREAD

**Issue by IDKLYFE** [abhishekmj303/ytm2spt#15]
after putting the secret client ID and rotating it many time a error saying
Error running command: error: invalid_client, error_description: Invalid client secret
happens
i even typed the secret client ID just incase and it still persisted

**Comment by abhishekmj303** [comment]
Try deleting the `.cache-<username>` file created by the app.

**Comment by IDKLYFE** [comment]
thank you very much i fixed my going to a file that i had from before when i tried doing this without the ui and i just changed the secret client id from the config
