### ISSUE TITLE
Help with Syntax Error

### ISSUE THREAD

**Issue by jldobben** [abhishekmj303/ytm2spt#3]
Hey, I'm sorry but I'm super new to any sort of programming, I'm trying to get this to work, and I've downloaded the most recent Python. I'm on windows, and I believe I have correctly edited the env.bat file in notepad and ran it with python, and it has said that all 4 of my variables, including the ones I got from the Spotify developer dashboard, have been set. But I can't get through the next step (installing dependencies with the requirements.txt) because no matter what I write in python, it says syntax error and will not process anything. I tried copying and pasting exactly what was in your code into my python and it didn't work. I am also not sure how to edit my credentials in the next step with YouTube oauth, but if that's for private videos I could just unlist all the playlists I want to share. Help would be greatly appreciated, you can reply here, at my email jarroddobben@gmail.com, or through discord @c7ementine. Thank you!

**Comment by abhishekmj303** [comment]
- Don't open python to run anything. You should open the Windows Terminal app to run these commands.

- Open the terminal by right clicking in the folder in which the code is present.

- Edit the env.bat file in notepad and run those commands in the terminal

- All other commands can be directly copy pasted from the GitHub to the terminal.


If you are still stuck, post some screenshots here.

**Comment by jldobben** [comment]
hey, thanks for the help, but I'm still having trouble.

so I right click the ytm2spt-main in my file directory and click open in terminal, and when I put in the requirements installation or the youtube authorization I get this:
![Screenshot 2024-05-03 153844](https://github.com/abhishekmj303/ytm2spt/assets/168124136/e8c716a6-b5bc-47e3-935e-dd6547b4b20c)
and when I run the edited batch file that looks like this: 
![image](https://github.com/abhishekmj303/ytm2spt/assets/168124136/0a816a44-b5ba-4407-a242-f0b95eadafd1)
it looks like terminal opens for a split second before closing itself

**Comment by abhishekmj303** [comment]
- I think you don't have pip in the path. Follow this to configure pip and everything should work: https://stackoverflow.com/a/56678271

- And in the env.bat you should remove the `< `and `>` in the first three lines.

- You only need to run the env.bat once and yes it will open for a split second and close.

**Comment by jldobben** [comment]
Hey, here are some updates:

I've updated Powershell and Python to their most recent versions, but idk if that matters.

I got pip into the path and recognized by cmd, but this message comes up when I try to run <pip install -r requirements.txt>:

![image](https://github.com/abhishekmj303/ytm2spt/assets/168124136/32a3abd9-3d0f-4a19-8bfe-b3674489f2a8)

also, I restarted the entire process again bc my env.bat file was no longer opening a cmd window and then closing it right away, but just opening a completely empty black cmd window, and after re-inputting my information from Spotify it continues not to run anything, apparently. here is an uneventful picture of the blank screen in displays:

![image](https://github.com/abhishekmj303/ytm2spt/assets/168124136/fcdf0770-1449-4bdf-be77-2d9aba36a76b)

Finally, I just want to make sure what I am inputting for my Spotify account ID is correct, it's this number on my account page, right?

![image](https://github.com/abhishekmj303/ytm2spt/assets/168124136/042ea146-a8e7-477b-ad37-f0f4673b15e5)

Thanks so much for your help man, sorry that I'm getting caught on pretty basic tasks haha

**Comment by abhishekmj303** [comment]
- Yes the username is correct. And previously as I said, you need to remove those `<` and `>` from the env.bat file values.

- You need to run all the commands by opening the terminal by right clicking in the folder in which the code is present.

- After you open the terminal as above, and edit the env.bat file, copy paste the following commands:
```
pip install -r requirements.txt
env.bat
ytmusicapi oauth
```

- After this close and reopen the terminal. Run the commands to transfer playlists as given in the readme's usage section.

**Comment by jldobben** [comment]
thank you so much for your help! I got it to work by opening the folder in terminal, and I was able to transfer all of my youtube playlists. One problem I have is that this app hasn't really worked for playlists copied straight from youtube music (rather than youtube proper), is there anything I can do that would make that possible? If not that's ok, this app worked amazingly, thank you so much for this and for helping me out!

**Comment by abhishekmj303** [comment]
> One problem I have is that this app hasn't really worked for playlists copied straight from youtube music (rather than youtube proper)

What do you mean by this? Can you give an example of what is not working?

**Comment by jldobben** [comment]
here is a screenshot of the cmd window that usually disappears in an instant when using music.youtube.com instead of youtube.com, but only for sometimes?????
![image](https://github.com/abhishekmj303/ytm2spt/assets/168124136/d5276a8f-8311-42b6-a7f2-1fdae41662b1)

**Comment by jldobben** [comment]
Nvm I got it to work, the playlists just had to be public, and after a few goes I got everything I needed. Thank you so much man, this is a huge vouch to anyone in need of transfering YouTube to Spotify, all the details are incredible!
