### ISSUE TITLE
Env Variables dont appear to be capturing correctly

### ISSUE THREAD

**Issue by RumNCodeDev** [abhishekmj303/ytm2spt#4]
This took looks awesome, and hopefully I can get this to work. I have followed your steps to the best of my knowledge, and the terminal is showing that the environment variables were indeed saved, however, when the 2nd command runs to actually do the migration, its stating that I need to set my environment variables still. 

Ran on windows both in `powershell`, and `git bash` terminals

Side note, my spotify ID was also in quotes originally, just playing around a few times trying to get this to work

![image](https://github.com/abhishekmj303/ytm2spt/assets/124214345/165082f0-13ac-4b74-a514-6e02553e9bef)

**Comment by RumNCodeDev** [comment]
I just replaced the spot in the code that looks for the environment variables and just set them directly, and now it appears to be working. Not sure why my terminals dont appear to recognize the variables set in the env

![image](https://github.com/abhishekmj303/ytm2spt/assets/124214345/6276eced-2741-4533-9b0a-a2ddd29a01a1)

**Comment by RumNCodeDev** [comment]
I ran the command in both, in the screenshot above they were ran in the same terminal 1 after another

**Comment by abhishekmj303** [comment]
No what I was telling was the instructions were for windows powershell not for git bash. Git bash follows a different way.

Try to follow the linux's way to set the environment variables. This is because it will work in git bash.

**Comment by RumNCodeDev** [comment]
Like i said, love your work though, great job, I just think theres something potentially wrong with the env variables for windows setup. But after just hard coding the variables into the file, it appears to have worked great. Obviously I have not listened to them yet to see what weirdness might have happened in the fuzzy matches, but im sure it saved me countless hours of manual work. 

![image](https://github.com/abhishekmj303/ytm2spt/assets/124214345/49f6b52f-6308-43b9-9357-7d75fb09f9f0)

**Comment by abhishekmj303** [comment]
- The thing is I don't have a windows device to test these. So I'm relying on the user's bug report and internet to support windows. 

- Can you share your exact env.bat with random values as text here? I'll look into it.

- And also yeah, thanks for the feedback. I'll make it to print the list of missed out songs at the end.

**Comment by abhishekmj303** [comment]
You need to close all the terminals and reopen them to activate the environment variables. (https://superuser.com/a/975002)

Test this by running `echo %SPOTIFY_USER_ID%` to check if it is actually set in the current session.

- I'll add this into the readme.

- The thing is I don't have a windows device to test these. So I'm relying on the user's bug report and internet to support windows.

- And also yeah, thanks for the feedback. I'll make it to print the list of missed out songs at the end.

**Comment by abhishekmj303** [comment]
Commit e20a77b25ae4bc390def3976a63352528418f9e4 and aa5c57e10ecd0361b53131af52f67d11f25cfad9 fixes this.
