### ISSUE TITLE
Script hangs after getting songs from youtube

### ISSUE THREAD

**Issue by darkmagi2** [abhishekmj303/ytm2spt#5]
When running the script, it seems to hang with no output after pulling the Youtube playlist. At first I thought it was because the playlist was very large (over 4k songs) but when I do a smaller playlist (and even a -l 10) the script seems to hang forever. I tried a dry run and the output got a little bit further, but still nothing seems to happen. Sample outputs below:

python src/main.py -yt "https://music.youtube.com/playlist\?list\=PL62yFmvrKGJkp2jc3c5qvpsz9oHC0fOH-" -l 10       
INFO - Youtube Playlist ID: PL62yFmvrKGJkp2jc3c5qvpsz9oHC0fOH-
INFO - Youtube Playlist Name: Shaky Knees 2023
.... 

Dry run:

python src/main.py -yt "https://music.youtube.com/playlist\?list\=PL62yFmvrKGJkp2jc3c5qvpsz9oHC0fOH-" -l 10 -d     
INFO - Youtube Playlist ID: PL62yFmvrKGJkp2jc3c5qvpsz9oHC0fOH-
INFO - Youtube Playlist Name: Shaky Knees 2023
INFO - Dryrun mode enabled. No songs will be added to Spotify.
INFO - Got 10 songs from Youtube Playlist
...

This is on Ubuntu 23.10 and Python 3.11.6

**Comment by bakerfugu** [comment]
I think you're just using a weird URL. When I click on the link you provided it doesn't take me to a playlist.

I was able to find your playlist by changing the URL to this though:
https://music.youtube.com/playlist?list=PL62yFmvrKGJkp2jc3c5qvpsz9oHC0fOH-

So it seems like the backslashes in your URL might be messing it up?

I was able to get it to work just by changing the command slightly too
```console
$ python3 src/main.py -d -yt PL62yFmvrKGJkp2jc3c5qvpsz9oHC0fOH-

INFO - Youtube Playlist ID: PL62yFmvrKGJkp2jc3c5qvpsz9oHC0fOH-
INFO - Youtube Playlist Name: Shaky Knees 2023
INFO - Dryrun mode enabled. No songs will be added to Spotify.
INFO - Got 1078 songs from Youtube Playlist
Fuzy match found [('Desure', 100), ('Desire', 83), ('Ellise', 50)]
Fuzy match found [('Desure', 100), ('Desire', 83), ('Lestmor', 46)]
Fuzy match found [('Desure', 100), ('Desire', 83), ('Grandmas House', 40)]
Fuzy match found [('Desure', 100), ('Desire', 83), ('DZ Deathrays', 33)]
Fuzy match found [('Desure', 100), ('Desire', 83), ('Petty', 18)]
Fuzy match found [('Desure', 100), ('Desire', 83), ('Donnie Ray', 38)]
```

**Comment by darkmagi2** [comment]
> I think you're just using a weird URL. When I click on the link you provided it doesn't take me to a playlist.
> 
> I was able to find your playlist by changing the URL to this though: https://music.youtube.com/playlist?list=PL62yFmvrKGJkp2jc3c5qvpsz9oHC0fOH-
> 
> So it seems like the backslashes in your URL might be messing it up?
> 
> I was able to get it to work just by changing the command slightly too
> 
> ```
> $ python3 src/main.py -d -yt PL62yFmvrKGJkp2jc3c5qvpsz9oHC0fOH-
> 
> INFO - Youtube Playlist ID: PL62yFmvrKGJkp2jc3c5qvpsz9oHC0fOH-
> INFO - Youtube Playlist Name: Shaky Knees 2023
> INFO - Dryrun mode enabled. No songs will be added to Spotify.
> INFO - Got 1078 songs from Youtube Playlist
> Fuzy match found [('Desure', 100), ('Desire', 83), ('Ellise', 50)]
> Fuzy match found [('Desure', 100), ('Desire', 83), ('Lestmor', 46)]
> Fuzy match found [('Desure', 100), ('Desire', 83), ('Grandmas House', 40)]
> Fuzy match found [('Desure', 100), ('Desire', 83), ('DZ Deathrays', 33)]
> Fuzy match found [('Desure', 100), ('Desire', 83), ('Petty', 18)]
> Fuzy match found [('Desure', 100), ('Desire', 83), ('Donnie Ray', 38)]
> ```
> 
> I'm not a project maintainer by the way, I was just importing some stuff and saw your question.

I wish this was the case (I did actually notice the escaped characters and tried without them).

I tried again with just the playlist ID like you did above and it still hung in the same spot. If it's working for you and not me it must be something on my end though...

`python src/main.py -yt "PL62yFmvrKGJkp2jc3c5qvpsz9oHC0fOH-"                                                      
INFO - Youtube Playlist ID: PL62yFmvrKGJkp2jc3c5qvpsz9oHC0fOH-
INFO - Youtube Playlist Name: Shaky Knees 2023`
...
``

**Comment by darkmagi2** [comment]
Tried on a WSL version of Ubuntu 22.04 and Python 3.10.12 and got different results but still a failure. Definitely seems to be some Python version issues going on. Dry run works:

```
python3 src/main.py -yt "https://music.youtube.com/playlist\?list\=PL62yFmvrKGJkp2jc3c5qvpsz9oHC0f
OH-" -l 10 -d
INFO - Youtube Playlist ID: PL62yFmvrKGJkp2jc3c5qvpsz9oHC0fOH-
INFO - Youtube Playlist Name: Shaky Knees 2023
INFO - Dryrun mode enabled. No songs will be added to Spotify.
INFO - Got 10 songs from Youtube Playlist
Fuzy match found [('Desure', 100), ('Tom Lehrer', 38), ('Palaye Royale', 32)]
Fuzy match found [('Desure', 100), ('Leezy', 36), ('Ramirez', 31)]
Fuzy match found [('Desure', 100), ('Grandmas House', 40), ('Nettspend', 40)]
Fuzy match found [('Desure', 100), ('Evanescence', 35), ('Survive Said The Prophet', 33)]
Fuzy match found [('Desure', 100), ('Cesária Evora', 44), ('Pretty Patterns', 38)]
Fuzy match found [('Desure', 100), ('Prefuse 73', 38), ('Tom Fuller', 25)]
Fuzy match found [('Desure', 100), ('Drake', 55), ('Presence', 43)]
Fuzy match found [('Desure', 100), ('Beatrice', 43), ('Evanescence', 35)]
Fuzy match found [('Desure', 100), ('Embrace', 46), ('Terry MacAlmon', 20)]
Fuzy match found [('Desure', 100), ('Pinegrove', 40), ('Gabriel', 31)]
```

But now the actual run fails:

```
python3 src/main.py -yt "https://music.youtube.com/playlist\?list\=PL62yFmvrKGJkp2jc3c5qvpsz9oHC0fOH-" -l 10
INFO - Youtube Playlist ID: PL62yFmvrKGJkp2jc3c5qvpsz9oHC0fOH-
INFO - Youtube Playlist Name: Shaky Knees 2023
Traceback (most recent call last):
  File "/home/shawn/workspace/ytm2spt/src/main.py", line 149, in <module>
    spotify_id = get_spotify_playlist_id(spotify_arg, spotify_playlist_name)
  File "/home/shawn/workspace/ytm2spt/src/main.py", line 51, in get_spotify_playlist_id
    return sp.create_playlist(yt.get_playlist_title())
  File "/home/shawn/workspace/ytm2spt/src/spotify.py", line 86, in create_playlist
    return playlist['id']
```

**Comment by darkmagi2** [comment]
I'm still not sure what was going on with my Ubuntu 23.10/Python 3.11.6 installation, however I found my issue with the Python 3.10.12 install and it was totally my fault. I incorrectly had my email as my Spotify user ID instead of my actual user id. Oops!

**Comment by abhishekmj303** [comment]
@darkmagi2 There seems to be a bug in the 'requests' library (https://stackoverflow.com/q/45267003).

Setting a timeout to the requests doesn't hang the script. It will fail and give the traceback error. I'll fix this, so I'm reopening the issue.
