### ISSUE TITLE
Illegal redirect_uri

### ISSUE THREAD

**Issue by Brahamdeep** [abhishekmj303/ytm2spt#6]
when i run the script i get redirected to - 
 https://accounts.spotify.com/authorize?client_id=+52f3fd98b3854a7caa1ac655ea0508b5&response_type=code&redirect_uri=%22http%3A%2F%2Flocalhost%3A8888%2Fcallback%22&scope=playlist-read-collaborative+playlist-modify-private+playlist-modify-public+playlist-read-private+ugc-image-upload
 
 and in the cmd it asks me to enter the url you were directed to:
 
 what to do now ??

**Comment by abhishekmj303** [comment]
Can you tell which command you ran?

**Comment by Brahamdeep** [comment]
# Pass just the youtube playlist ID
# Set a custom name for the playlist
$ python src/main.py -yt "CLAK5uy_lBNUteBRencHzKelu5iDHwLF6mYqjL-JU" -spname "Pop Certified"


i ran this one with obviously a different playlist and name

**Comment by abhishekmj303** [comment]
When the link only opened in the browser and the browser already had Spotify logged in, you should ideally be redirected back to the app.

But if the browser doesn't redirect back when logged in and your url looks like this "http://localhost:8888/callback?code=" or something similar. You can copy that code and paste it into the terminal.

If you are not even getting the localhost url in the browser and the page keeps loading, you can just close the tab and the app should continue working.

**Comment by abhishekmj303** [comment]
If you are still unsure what's happening, you can share a screenshot so that I can help you with the problem.

**Comment by Brahamdeep** [comment]
Dude i tried the same steps which i tried yesterday and it worked now before trying to put it into the code 💀. Thanks anyway dude loved your app. Also side question i have 1128 tracks so do you have any idea how much time will this take ?!?!

**Comment by abhishekmj303** [comment]
Great to know it works now! Not sure what was happening before.

As far as I have used, it takes around 2 to 3 minutes for a 50 songs playlist. Not sure if it would be the same for larger playlists.

If the issue is resolved close the issue.

**Comment by Brahamdeep** [comment]
Ohk thank you for you help again :D
