### ISSUE TITLE
unable to use on mac on vs code 

### ISSUE THREAD

**Issue by siddhantbaliyan** [abhishekmj303/ytm2spt#7]
i clone your project on vs code please tell me how it run on mac or provide tutorial on yt or something

**Comment by abhishekmj303** [comment]
You just need to follow steps given in the GitHub. There is no specific tutorial needed for mac.

Setup (only once):
- Spotify developer account
- Setting Environment Variables Mac
- Install Dependencies
- Youtube OAuth (Only for private playlists)

For usage examples are also given.

**Comment by siddhantbaliyan** [comment]
main file is not running

**Comment by abhishekmj303** [comment]
Can you tell what all did you do before running those?

Did you go through the setup process and edit the .env file?

Post the errors you are getting from the terminal.

**Comment by siddhantbaliyan** [comment]
![Uploading Screenshot 2024-06-16 at 5.05.42 PM.png…]()

**Comment by siddhantbaliyan** [comment]
<img width="1440" alt="Screenshot 2024-06-16 at 5 05 42 PM" src="https://github.com/abhishekmj303/ytm2spt/assets/52606880/0bd5f22e-1f5a-49ab-896e-811acac69831">

**Comment by siddhantbaliyan** [comment]
am i bot !!! who is not able to use this code

**Comment by abhishekmj303** [comment]
Did you run?

```
pip install -r requirements.txt
```

**Comment by siddhantbaliyan** [comment]
yes i already did

**Comment by abhishekmj303** [comment]
What is the output of this?

```
python -V
which python
which pip
```

**Comment by siddhantbaliyan** [comment]
<img width="1440" alt="Screenshot 2024-06-16 at 5 05 42 PM" src="https://github.com/abhishekmj303/ytm2spt/assets/52606880/dd4e7e8f-00df-4c2e-a3bb-278dd9b1ebfb">

**Comment by siddhantbaliyan** [comment]
<img width="1440" alt="Screenshot 2024-06-16 at 8 24 51 PM" src="https://github.com/abhishekmj303/ytm2spt/assets/52606880/b4daf471-d680-4bd2-aa83-c5afc724757c">

**Comment by abhishekmj303** [comment]
I see what's the issue here. You are running python from anaconda but the packages are installed in the default python of the mac.

Run this to deactivate the anaconda environment:
```
conda deactivate
```

After running this if you don't see the `(base)` in the prompt, conda is deactivated successfully.
You can then run:
```
python src/main.py
```

**Comment by siddhantbaliyan** [comment]
<img width="1440" alt="Screenshot 2024-06-16 at 8 55 47 PM" src="https://github.com/abhishekmj303/ytm2spt/assets/52606880/f40458d2-5cf3-4359-bdb5-72f33f2962d6">

**Comment by siddhantbaliyan** [comment]
should i run requrement command again

**Comment by abhishekmj303** [comment]
Try python3

**Comment by siddhantbaliyan** [comment]
cmd

**Comment by siddhantbaliyan** [comment]
okay installing python 3 from homebrew

**Comment by abhishekmj303** [comment]
```
python3 src/main.py
```

You'll get a help message on how to use.

**Comment by abhishekmj303** [comment]
> okay installing python 3 from homebrew

No. Not required

**Comment by siddhantbaliyan** [comment]
<img width="1440" alt="Screenshot 2024-06-16 at 9 06 53 PM" src="https://github.com/abhishekmj303/ytm2spt/assets/52606880/4cc510ca-f159-4bbe-83fc-b2acbe305ab7">
now it's showing that

**Comment by siddhantbaliyan** [comment]
now it's showing that 
<img width="1440" alt="Screenshot 2024-06-16 at 9 09 09 PM" src="https://github.com/abhishekmj303/ytm2spt/assets/52606880/0c716f7a-451d-4706-a1eb-60252879438d">

**Comment by abhishekmj303** [comment]
Now you can run the script. It's working. You can ignore the syntax warning.

See the usage and examples section in the readme for sample commands.

Keep in mind. **You need to replace `python` with `python3` in all of the commands you run.**

**Comment by siddhantbaliyan** [comment]
okay i'll try

**Comment by siddhantbaliyan** [comment]
what command i should use for yt public playlist copy to spotify account it even asks for spotify account access but did not copied to spotify what should i add to cmd
<img width="1440" alt="Screenshot 2024-06-16 at 9 45 12 PM" src="https://github.com/abhishekmj303/ytm2spt/assets/52606880/3fd3ef0a-07d7-4892-a514-4217ae75ded6">

**Comment by siddhantbaliyan** [comment]
mostly work is done

**Comment by siddhantbaliyan** [comment]
see last screenshot

**Comment by abhishekmj303** [comment]
In `.env` the spotify username is not the email address. You will get the username here: https://www.spotify.com/in-en/account/profile/

**Comment by siddhantbaliyan** [comment]
<img width="1440" alt="Screenshot 2024-06-16 at 9 57 01 PM" src="https://github.com/abhishekmj303/ytm2spt/assets/52606880/a946cdc3-2570-4068-b1b4-860c78974c90">

**Comment by abhishekmj303** [comment]
Did you run this again after editing the file?
```
source .env
```

**Comment by siddhantbaliyan** [comment]
oops moment

**Comment by siddhantbaliyan** [comment]
transfering in process , thank you abhishekmj sir

**Comment by siddhantbaliyan** [comment]
some songs are not exact but success rate is around 92%
